### ISSUE TITLE
Cannot change theme variant

### ISSUE THREAD

**Issue by lostl1ght** [Yagua/nebulous.nvim#13]
### Bug description

Since ade7d7d I can no longer change theme variant using `setup` function.

### Steps to reproduce

```lua
require('nebulous').setup({
    variant = 'midnight',
})
```

### Additional information

I have discovered that this may happen due to `setup_scheme` function being called twice.
The first time it is called with user parameters by `setup` function. 
The second time it is called from `nebulous.vim` file with default parameters.

**Comment by Yagua** [comment]
Hi buddy, how are you, thanks for bringing this problem to our attention.
I wanted to ask you where you are calling the setup function, as I have tested it on two computers and it works correctly both in a module loaded automatically by the editor (in the after directory) and in the 'config' callback that the 'Packer' package manager has.

I show you briefly my configuration.
it is located in the after/plugin directory in a file named like the theme.

![image](https://user-images.githubusercontent.com/65829671/143779240-39ade441-6113-4b2e-9b53-da027f89869e.png)

**Comment by lostl1ght** [comment]
I have a loader function. It is a wrapper around `packer`:
![image](https://user-images.githubusercontent.com/61948252/143779720-17ace6ff-455b-4aaf-98d7-0881b1e65146.png)

It is called from `init.lua` file: 
![image](https://user-images.githubusercontent.com/61948252/143779678-e1da5d7e-e912-4f35-93f7-385e73b92972.png)

Parameter for the loader is a table and looks like this:
![image](https://user-images.githubusercontent.com/61948252/143779756-66d9a2c5-d2c1-4ace-85c4-d8bdc002e3f6.png)

Config looks like this:
![image](https://user-images.githubusercontent.com/61948252/143779783-241349b6-bcd9-4b4b-8488-434d97d62be9.png)

`llvim.style` is just a global,  and if I replace it with a string `'midnight'` I still get a `night` variant.

**Comment by Yagua** [comment]
I have cloned your configuration and I am changing the value of the global variable llvim.style and apparently on my pc it works.

![image](https://user-images.githubusercontent.com/65829671/143781255-11400462-e90c-4303-9c89-de1d9b70b977.png)

![image](https://user-images.githubusercontent.com/65829671/143781328-f644bec9-452c-4a31-9f0e-c8d26bbfb2f0.png)

do you think it is possible to verify if really the value you give to this variable is arriving correctly to the theme setup, generally when a value is not specified in the "variant" attribute it will be set by default night

however it is weird because in my machine it works

**Comment by lostl1ght** [comment]
I have added a print inside set_scheme:
![image](https://user-images.githubusercontent.com/61948252/143782830-3e78983a-9ab0-4b1c-a0ff-cf3e14e5bd09.png)

And this is what I see when I start nvim:
![image](https://user-images.githubusercontent.com/61948252/143782820-45af8e49-7e1b-47b9-b29b-b611f73c3bee.png)

You can see `set_scheme` is called twice.

I've also used [inspect](https://github.com/kikito/inspect.lua) library to print tables:
![image](https://user-images.githubusercontent.com/61948252/143783384-8366b00c-bf04-4073-b149-ec8ae82adac5.png)

And that's what I see:
![image](https://user-images.githubusercontent.com/61948252/143783399-5c6a71df-39ae-4e3f-b6a7-5aea00906c99.png)
![image](https://user-images.githubusercontent.com/61948252/143783405-03b6362d-3590-4881-a555-fe833c3781f2.png)

`setup_scheme` function is called twice.
The first 2 tables in the output are `opts` and `conf` from my config.
The third table is `nil` because `setup_scheme` is called without arguments so `opts` is `nil` and `conf` is the default fourth table.

So yes, the value arrives correctly but then the config gets changed to default by the second `setup_scheme` call.

**Comment by Yagua** [comment]
I understand, and upon review you are right, and I think I know where the problem is.
Try commenting out the line "require(" nebulous.utils").setup_scheme()" inside colors/nebulous.vim in the theme, that's where you overwrite the user configuration (just as you mentioned).
It is something that I see is causing problems and I will remove it from there, just as the readme mentions the theme is set by means of its setup function.

**Comment by lostl1ght** [comment]
Thank you, it helped.

As far as I'm concerned, plugins are loaded asynchronously. So maybe on your machine `nebulous.vim` is loaded before `nebulous.lua` and on mine vice versa. Maybe that's why you couldn't reproduce this issue.

**Comment by Yagua** [comment]
Solved in 9cb59ab
